version: "3.8"
services:
  client:
    stdin_open: true
    build:
      context: ./src/povargan-ui
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      REACT_APP_BACKEND_URL: https://api.thisfooddoesnotexist.com/
      PORT: 3030
  server:
    build: 
      context: ./src/povargan-server
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    environment:
      PORT: 5050
      FLASK_DEBUG: 1
