version: "3.8"
services:
  client:
    stdin_open: true
    build:
      context: ./src/povargan-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:5000/
  server:
    build: 
      context: ./src/povargan-server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1